### ISSUE TITLE
The simplest comparison to ham

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#2]
The simplest test comparison to ham would be an HMM of this shape:

```
--------
   |||||
   --------
```

two linear segments, with a collection of transitions between them in a range.

**Comment by matsen** [comment]
## The master challenge

Say we have an HMM laid out like
```
*-*-*
  | |
  *-*-*
```
emitting binary symbols.

Say the emission probabilities for the top three states are

0.1, 0.2, 0.3
0.9, 0.8, 0.7

and those on the bottom are

0.11, 0.13, 0.17
0.89, 0.87, 0.83

and the probability of continuing to the upper right state is 0.23.

Q: what are the marginal and Viterbi probabilities of the sequence 0, 1, 1?

**Comment by matsen** [comment]
I get (note these are "raw" probabilities, not log probs):

Ham test 1 marginal: 0.00149626
Ham test 1 viterbi: 0.00121161

**Comment by psathyrella** [comment]
maybe this ` (row 0 corresponds to state 0, etc) `  -->  `(column 0 corresponds to state 0, etc) `?

**Comment by psathyrella** [comment]
I get 0.00121 for the viterbi; I don't know what you mean by the marginal probability of the sequence. Does that mean the probability of the sequence, i.e. forward?

**Comment by psathyrella** [comment]
oh, I guess so, my fwd prob is 0.001496. full output:

```
viterbi path (log prob -6.7158):
  sequence: z o o z z 
  path:     t t b b b 

forward log prob: -6.50479
```

nice!

**Comment by psathyrella** [comment]
yaml, for future reference:

```
name: binample
tracks:
  bits: [z,o]
states:
- name: init
  transitions:
    top_left: 1.0
- name: top_left
  emissions:
    track: bits
    probs:
      z: 0.1
      o: 0.9
  transitions:
    top_middle: 1.
- name: top_middle
  emissions:
    track: bits
    probs:
      z: 0.2
      o: 0.8
  transitions:
    top_right: 0.23
    bottom_left: 0.77
- name: top_right
  emissions:
    track: bits
    probs:
      z: 0.3
      o: 0.7
  transitions:
    bottom_middle: 1.0
- name: bottom_left
  emissions:
    track: bits
    probs:
      z: 0.11
      o: 0.89
  transitions:
    bottom_middle: 1.0
- name: bottom_middle
  emissions:
    track: bits
    probs:
      z: 0.13
      o: 0.87
  transitions:
    bottom_right: 1.0
- name: bottom_right
  emissions:
    track: bits
    probs:
      z: 0.17
      o: 0.83
  transitions:
    end: 1.0

```
